apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-v
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: node-app-test:1.0
          ports:
            - containerPort: 3003
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: node-config-prop
            items:
              - key: config.properties
                path: config.properties
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30100
